# Generated by Django 5.2.6 on 2025-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0006_alter_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
