# Generated by Django 5.2.6 on 2025-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0007_alter_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
