# Generated by Django 5.2.6 on 2025-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0008_alter_task_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
