# Generated by Django 5.2.6 on 2025-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0004_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
