# Generated by Django 5.2.6 on 2025-09-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0005_task_slug_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
